//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork7Term.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cinema
    {
        public cinema()
        {
            this.session = new HashSet<session>();
            this.place = new HashSet<place>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string work_time { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<session> session { get; set; }
        public virtual ICollection<place> place { get; set; }
    }
}
