//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork7Term.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class film
    {
        public film()
        {
            this.film_profile_mark = new HashSet<film_profile_mark>();
            this.session = new HashSet<session>();
            this.actor = new HashSet<actor>();
            this.country = new HashSet<country>();
            this.genre = new HashSet<genre>();
            this.producer = new HashSet<producer>();
            this.screenwriter = new HashSet<screenwriter>();
        }
    
        public int id { get; set; }

        [Display(Name = "Фильм")]
        public string name { get; set; }

        [Display(Name = "Продолжительность")]
        public string duration { get; set; }

        [Display(Name = "Ограничение по возрасту")]
        public Nullable<int> age_limit { get; set; }

        [Display(Name = "Год выпуска")]
        public string release_year { get; set; }

        [Display(Name = "Описание")]
        public string description { get; set; }

        [Display(Name = "Средняя оценка")]
        public double average_mark { get; set; }
    
        public virtual ICollection<film_profile_mark> film_profile_mark { get; set; }
        public virtual ICollection<session> session { get; set; }

        [Display(Name = "Актеры")]
        public virtual ICollection<actor> actor { get; set; }

        [Display(Name = "Страны")]
        public virtual ICollection<country> country { get; set; }

        [Display(Name = "Жанры")]
        public virtual ICollection<genre> genre { get; set; }

        [Display(Name = "Режиссеры")]
        public virtual ICollection<producer> producer { get; set; }

        [Display(Name = "Сценаристы")]
        public virtual ICollection<screenwriter> screenwriter { get; set; }
    }
}
