//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork7Term.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark
    {
        public mark()
        {
            this.film_profile_mark = new HashSet<film_profile_mark>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int value { get; set; }
    
        public virtual ICollection<film_profile_mark> film_profile_mark { get; set; }
    }
}
