//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork7Term.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class place
    {
        public place()
        {
            this.ticket = new HashSet<ticket>();
            this.cinema = new HashSet<cinema>();
        }
    
        public int id { get; set; }
        public int range { get; set; }
        public int number { get; set; }
    
        public virtual ICollection<ticket> ticket { get; set; }
        public virtual ICollection<cinema> cinema { get; set; }
    }
}
