//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork7Term.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public profile()
        {
            this.film_profile_mark = new HashSet<film_profile_mark>();
            this.ticket = new HashSet<ticket>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public bool is_admin { get; set; }
    
        public virtual ICollection<film_profile_mark> film_profile_mark { get; set; }
        public virtual ICollection<ticket> ticket { get; set; }
    }
}
