//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork7Term.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class screenwriter
    {
        public screenwriter()
        {
            this.film = new HashSet<film>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<film> film { get; set; }
    }
}
