//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork7Term.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public bool is_bought { get; set; }
        public Nullable<int> profile_id { get; set; }
        public int cinema_id { get; set; }
        public int film_id { get; set; }
        public int place_id { get; set; }
    
        public virtual place place { get; set; }
        public virtual profile profile { get; set; }
        public virtual session session { get; set; }
    }
}
